services:
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - ./src:/src
      - ./docker/php:/usr/local/etc/php/conf.d
    working_dir: /src
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 82:8080
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/definitions
    environment:
      API_URL: definitions/swagger.yml
    depends_on:
      - app
